export default [
  "text-quarterary_on-brand",
  "text-placeholder_subtle",
  "text-tertiary_alt",
  "border-tertiary",
  "border-disabled_subtle",
  "border-brand-solid_alt",
  "fg-senary",
  "fg-disabled_subtle",
  "fg-brand-secondary",
  "bg-quarterary",
  "bg-overlay",
  "button-primary-border_hover",
  "button-secondary-shadow",
  "button-secondary-color-shadow",
  "button-tertiary-bg_hover",
  "button-tertiary-color-bg_hover",
  "button-primary-error-border_hover",
  "button-secondary-error-border_hover",
  "icon-fg-brand_on-brand",
  "featured-icon-light-fg-success",
  "featured-icon-dark-fg-success",
] as string[];
